[build-system]
requires = [
    "setuptools>=45",
]

build-backend = "setuptools.build_meta"

[project]
name = "py-lib3mf"
version = "VERSION"
description = "A python package for Lib3MF tools"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}

[tool.setuptools.package-data]
py_lib3mf = [ "*.so" ]
